package advanced

// buildSynergies creates all valid multi-class synergy bonuses
func buildSynergies() []SynergyBonus {
	return []SynergyBonus{
		{
			Primary:   ClassWarrior,
			Secondary: ClassMage,
			Name:      "Spellsword",
			Bonuses: StatBonuses{
				Strength:     5,
				Intelligence: 5,
				Mana:         20,
			},
		},
		{
			Primary:   ClassWarrior,
			Secondary: ClassCleric,
			Name:      "Crusader",
			Bonuses: StatBonuses{
				Health:       30,
				Strength:     5,
				Wisdom:       5,
				MagicDefense: 3,
			},
		},
		{
			Primary:   ClassRogue,
			Secondary: ClassMage,
			Name:      "Trickster",
			Bonuses: StatBonuses{
				Dexterity:    5,
				Intelligence: 5,
				CritChance:   0.05,
			},
		},
		{
			Primary:   ClassRogue,
			Secondary: ClassRanger,
			Name:      "Scout",
			Bonuses: StatBonuses{
				Dexterity: 8,
				Stamina:   20,
				Speed:     0.1,
			},
		},
		{
			Primary:   ClassMage,
			Secondary: ClassCleric,
			Name:      "Mystic",
			Bonuses: StatBonuses{
				Mana:         30,
				Intelligence: 5,
				Wisdom:       5,
			},
		},
		{
			Primary:   ClassBerserker,
			Secondary: ClassAssassin,
			Name:      "Reaver",
			Bonuses: StatBonuses{
				Strength:   7,
				Dexterity:  7,
				CritDamage: 0.3,
			},
		},
		{
			Primary:   ClassPaladin,
			Secondary: ClassCleric,
			Name:      "Divine Protector",
			Bonuses: StatBonuses{
				Health:       50,
				Wisdom:       8,
				Defense:      5,
				MagicDefense: 5,
			},
		},
		{
			Primary:   ClassNinja,
			Secondary: ClassMage,
			Name:      "Shadow Mage",
			Bonuses: StatBonuses{
				Dexterity:    6,
				Intelligence: 6,
				Mana:         25,
				Speed:        0.15,
			},
		},
		{
			Primary:   ClassDruid,
			Secondary: ClassRanger,
			Name:      "Beastmaster",
			Bonuses: StatBonuses{
				Wisdom:    7,
				Dexterity: 5,
				Stamina:   25,
			},
		},
		{
			Primary:   ClassBard,
			Secondary: ClassRogue,
			Name:      "Swashbuckler",
			Bonuses: StatBonuses{
				Charisma:  8,
				Dexterity: 6,
				Speed:     0.12,
			},
		},
		{
			Primary:   ClassElementalist,
			Secondary: ClassDruid,
			Name:      "Geomancer",
			Bonuses: StatBonuses{
				Intelligence: 8,
				Wisdom:       6,
				Mana:         35,
			},
		},
		{
			Primary:   ClassKnight,
			Secondary: ClassBerserker,
			Name:      "Vanguard",
			Bonuses: StatBonuses{
				Health:   60,
				Strength: 8,
				Defense:  6,
			},
		},
		{
			Primary:   ClassNecromancer,
			Secondary: ClassAssassin,
			Name:      "Death Knight",
			Bonuses: StatBonuses{
				Intelligence: 7,
				Dexterity:    5,
				CritDamage:   0.4,
			},
		},
		{
			Primary:   ClassEnchanter,
			Secondary: ClassBard,
			Name:      "Illusionist",
			Bonuses: StatBonuses{
				Intelligence: 6,
				Charisma:     8,
				Mana:         30,
			},
		},
		{
			Primary:   ClassRanger,
			Secondary: ClassDruid,
			Name:      "Warden",
			Bonuses: StatBonuses{
				Dexterity: 6,
				Wisdom:    6,
				Stamina:   30,
			},
		},
	}
}

// createWarriorTalentTree constructs the Warrior class talent tree with offensive, defensive, and utility talents.
func createWarriorTalentTree() *TalentTree {
	return &TalentTree{
		Name:    "Warrior Talents",
		ClassID: ClassWarrior,
		Offensive: []TalentDefinition{
			{
				ID:          "warrior_power_strike",
				Name:        "Power Strike",
				Description: "Increases melee damage",
				Category:    CategoryOffensive,
				MaxRank:     5,
				Bonuses:     StatBonuses{Strength: 2},
			},
			{
				ID:          "warrior_critical_hit",
				Name:        "Critical Hit",
				Description: "Increases critical strike chance",
				Category:    CategoryOffensive,
				MaxRank:     5,
				Bonuses:     StatBonuses{CritChance: 0.02},
			},
			{
				ID:            "warrior_weapon_mastery",
				Name:          "Weapon Mastery",
				Description:   "Master of all weapons",
				Category:      CategoryOffensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"warrior_power_strike"},
				Bonuses:       StatBonuses{Strength: 3, CritDamage: 0.1},
			},
			{
				ID:            "warrior_berserker_rage",
				Name:          "Berserker Rage",
				Description:   "Trade defense for overwhelming offense",
				Category:      CategoryOffensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"warrior_weapon_mastery"},
				Bonuses:       StatBonuses{Strength: 5, CritDamage: 0.2, Defense: -2},
			},
			{
				ID:            "warrior_execute",
				Name:          "Execute",
				Description:   "Deal massive damage to low-health enemies",
				Category:      CategoryOffensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"warrior_critical_hit"},
				Bonuses:       StatBonuses{CritDamage: 0.15},
			},
			{
				ID:            "warrior_whirlwind",
				Name:          "Whirlwind",
				Description:   "Attack multiple enemies at once",
				Category:      CategoryOffensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"warrior_weapon_mastery"},
				Bonuses:       StatBonuses{Strength: 2, Stamina: 10},
			},
			{
				ID:            "warrior_bloodlust",
				Name:          "Bloodlust",
				Description:   "Gain strength from defeating enemies",
				Category:      CategoryOffensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"warrior_berserker_rage"},
				Bonuses:       StatBonuses{Strength: 4, CritChance: 0.03},
			},
			{
				ID:            "warrior_dual_wield",
				Name:          "Dual Wield",
				Description:   "Fight with two weapons",
				Category:      CategoryOffensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"warrior_weapon_mastery"},
				Bonuses:       StatBonuses{Dexterity: 3, CritChance: 0.04},
			},
			{
				ID:            "warrior_cleave",
				Name:          "Cleave",
				Description:   "Devastating area attacks",
				Category:      CategoryOffensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"warrior_whirlwind"},
				Bonuses:       StatBonuses{Strength: 3},
			},
			{
				ID:            "warrior_titan_strength",
				Name:          "Titan Strength",
				Description:   "Ultimate physical power",
				Category:      CategoryOffensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"warrior_bloodlust"},
				Bonuses:       StatBonuses{Strength: 5, Health: 20},
			},
		},
		Defensive: []TalentDefinition{
			{
				ID:          "warrior_iron_skin",
				Name:        "Iron Skin",
				Description: "Increases physical defense",
				Category:    CategoryDefensive,
				MaxRank:     5,
				Bonuses:     StatBonuses{Defense: 2},
			},
			{
				ID:          "warrior_vitality",
				Name:        "Vitality",
				Description: "Increases maximum health",
				Category:    CategoryDefensive,
				MaxRank:     5,
				Bonuses:     StatBonuses{Health: 20},
			},
			{
				ID:            "warrior_shield_mastery",
				Name:          "Shield Mastery",
				Description:   "Expert shield use",
				Category:      CategoryDefensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"warrior_iron_skin"},
				Bonuses:       StatBonuses{Defense: 3, Health: 15},
			},
			{
				ID:            "warrior_fortitude",
				Name:          "Fortitude",
				Description:   "Resist status effects",
				Category:      CategoryDefensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"warrior_vitality"},
				Bonuses:       StatBonuses{Health: 25, Defense: 2},
			},
			{
				ID:            "warrior_last_stand",
				Name:          "Last Stand",
				Description:   "Survive lethal damage once per combat",
				Category:      CategoryDefensive,
				MaxRank:       1,
				Prerequisites: []TalentID{"warrior_fortitude"},
				Bonuses:       StatBonuses{Health: 50},
			},
			{
				ID:            "warrior_armor_specialization",
				Name:          "Armor Specialization",
				Description:   "Enhanced effectiveness from armor",
				Category:      CategoryDefensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"warrior_shield_mastery"},
				Bonuses:       StatBonuses{Defense: 3, MagicDefense: 2},
			},
			{
				ID:            "warrior_parry",
				Name:          "Parry",
				Description:   "Deflect incoming attacks",
				Category:      CategoryDefensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"warrior_shield_mastery"},
				Bonuses:       StatBonuses{Defense: 4},
			},
			{
				ID:            "warrior_endurance",
				Name:          "Endurance",
				Description:   "Increased stamina regeneration",
				Category:      CategoryDefensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"warrior_vitality"},
				Bonuses:       StatBonuses{Stamina: 15, Health: 10},
			},
			{
				ID:            "warrior_indomitable",
				Name:          "Indomitable",
				Description:   "Immune to knockback",
				Category:      CategoryDefensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"warrior_fortitude"},
				Bonuses:       StatBonuses{Defense: 5, Health: 30},
			},
			{
				ID:            "warrior_immovable_object",
				Name:          "Immovable Object",
				Description:   "Ultimate defensive stance",
				Category:      CategoryDefensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"warrior_indomitable", "warrior_armor_specialization"},
				Bonuses:       StatBonuses{Defense: 8, MagicDefense: 5, Health: 40},
			},
		},
		Utility: []TalentDefinition{
			{
				ID:          "warrior_charge",
				Name:        "Charge",
				Description: "Rush to enemies",
				Category:    CategoryUtility,
				MaxRank:     3,
				Bonuses:     StatBonuses{Speed: 0.05, Stamina: 10},
			},
			{
				ID:          "warrior_rally",
				Name:        "Rally",
				Description: "Inspire nearby allies",
				Category:    CategoryUtility,
				MaxRank:     3,
				Bonuses:     StatBonuses{Charisma: 3, Health: 15},
			},
			{
				ID:            "warrior_battle_shout",
				Name:          "Battle Shout",
				Description:   "Boost party morale",
				Category:      CategoryUtility,
				MaxRank:       5,
				Prerequisites: []TalentID{"warrior_rally"},
				Bonuses:       StatBonuses{Charisma: 4, Strength: 2},
			},
			{
				ID:            "warrior_intimidation",
				Name:          "Intimidation",
				Description:   "Frighten enemies",
				Category:      CategoryUtility,
				MaxRank:       3,
				Prerequisites: []TalentID{"warrior_battle_shout"},
				Bonuses:       StatBonuses{Charisma: 5},
			},
			{
				ID:          "warrior_tactical_awareness",
				Name:        "Tactical Awareness",
				Description: "Better positioning",
				Category:    CategoryUtility,
				MaxRank:     5,
				Bonuses:     StatBonuses{Wisdom: 2, Dexterity: 1},
			},
			{
				ID:            "warrior_second_wind",
				Name:          "Second Wind",
				Description:   "Recover stamina in combat",
				Category:      CategoryUtility,
				MaxRank:       3,
				Prerequisites: []TalentID{"warrior_charge"},
				Bonuses:       StatBonuses{Stamina: 20},
			},
			{
				ID:            "warrior_commanding_presence",
				Name:          "Commanding Presence",
				Description:   "Natural leader",
				Category:      CategoryUtility,
				MaxRank:       5,
				Prerequisites: []TalentID{"warrior_intimidation"},
				Bonuses:       StatBonuses{Charisma: 6, Wisdom: 3},
			},
			{
				ID:            "warrior_field_medic",
				Name:          "Field Medic",
				Description:   "Basic healing knowledge",
				Category:      CategoryUtility,
				MaxRank:       3,
				Prerequisites: []TalentID{"warrior_tactical_awareness"},
				Bonuses:       StatBonuses{Wisdom: 4, Health: 20},
			},
			{
				ID:            "warrior_rapid_recovery",
				Name:          "Rapid Recovery",
				Description:   "Faster health regeneration",
				Category:      CategoryUtility,
				MaxRank:       5,
				Prerequisites: []TalentID{"warrior_second_wind"},
				Bonuses:       StatBonuses{Health: 25, Stamina: 15},
			},
			{
				ID:            "warrior_legendary_hero",
				Name:          "Legendary Hero",
				Description:   "Master of combat and leadership",
				Category:      CategoryUtility,
				MaxRank:       5,
				Prerequisites: []TalentID{"warrior_commanding_presence"},
				Bonuses:       StatBonuses{Charisma: 8, Strength: 4, Wisdom: 4},
			},
		},
	}
}

// createMageTalentTree constructs the Mage class talent tree with offensive, defensive, and utility talents.
func createMageTalentTree() *TalentTree {
	return &TalentTree{
		Name:    "Mage Talents",
		ClassID: ClassMage,
		Offensive: []TalentDefinition{
			{
				ID:          "mage_arcane_power",
				Name:        "Arcane Power",
				Description: "Increases spell damage",
				Category:    CategoryOffensive,
				MaxRank:     5,
				Bonuses:     StatBonuses{Intelligence: 3},
			},
			{
				ID:          "mage_spell_crit",
				Name:        "Spell Critical",
				Description: "Spells can critically hit",
				Category:    CategoryOffensive,
				MaxRank:     5,
				Bonuses:     StatBonuses{CritChance: 0.02, Intelligence: 1},
			},
			{
				ID:            "mage_fireball",
				Name:          "Fireball Mastery",
				Description:   "Enhanced fire spells",
				Category:      CategoryOffensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"mage_arcane_power"},
				Bonuses:       StatBonuses{Intelligence: 4, CritDamage: 0.08},
			},
			{
				ID:            "mage_frost_nova",
				Name:          "Frost Nova",
				Description:   "Freeze enemies in place",
				Category:      CategoryOffensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"mage_arcane_power"},
				Bonuses:       StatBonuses{Intelligence: 3, Wisdom: 2},
			},
			{
				ID:            "mage_lightning_bolt",
				Name:          "Lightning Bolt",
				Description:   "Chain lightning attacks",
				Category:      CategoryOffensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"mage_spell_crit"},
				Bonuses:       StatBonuses{Intelligence: 4, CritChance: 0.03},
			},
			{
				ID:          "mage_arcane_missiles",
				Name:        "Arcane Missiles",
				Description: "Rapid magical projectiles",
				Category:    CategoryOffensive,
				MaxRank:     5,
				Bonuses:     StatBonuses{Intelligence: 2, Mana: 15},
			},
			{
				ID:            "mage_meteor",
				Name:          "Meteor",
				Description:   "Summon devastating meteors",
				Category:      CategoryOffensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"mage_fireball"},
				Bonuses:       StatBonuses{Intelligence: 6, CritDamage: 0.15},
			},
			{
				ID:            "mage_blizzard",
				Name:          "Blizzard",
				Description:   "Area ice storm",
				Category:      CategoryOffensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"mage_frost_nova"},
				Bonuses:       StatBonuses{Intelligence: 5, Wisdom: 3},
			},
			{
				ID:            "mage_time_warp",
				Name:          "Time Warp",
				Description:   "Manipulate time for extra casts",
				Category:      CategoryOffensive,
				MaxRank:       1,
				Prerequisites: []TalentID{"mage_arcane_missiles"},
				Bonuses:       StatBonuses{Intelligence: 10, Mana: 50},
			},
			{
				ID:            "mage_apocalypse",
				Name:          "Apocalypse",
				Description:   "Ultimate magical destruction",
				Category:      CategoryOffensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"mage_meteor", "mage_blizzard"},
				Bonuses:       StatBonuses{Intelligence: 8, CritDamage: 0.25},
			},
		},
		Defensive: []TalentDefinition{
			{
				ID:          "mage_mana_shield",
				Name:        "Mana Shield",
				Description: "Convert mana to damage absorption",
				Category:    CategoryDefensive,
				MaxRank:     5,
				Bonuses:     StatBonuses{Mana: 20, MagicDefense: 2},
			},
			{
				ID:          "mage_ice_armor",
				Name:        "Ice Armor",
				Description: "Frozen protective barrier",
				Category:    CategoryDefensive,
				MaxRank:     5,
				Bonuses:     StatBonuses{Defense: 3, MagicDefense: 3},
			},
			{
				ID:          "mage_spell_resistance",
				Name:        "Spell Resistance",
				Description: "Resist hostile magic",
				Category:    CategoryDefensive,
				MaxRank:     5,
				Bonuses:     StatBonuses{MagicDefense: 4},
			},
			{
				ID:            "mage_arcane_barrier",
				Name:          "Arcane Barrier",
				Description:   "Powerful magical shield",
				Category:      CategoryDefensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"mage_mana_shield"},
				Bonuses:       StatBonuses{Mana: 25, MagicDefense: 4},
			},
			{
				ID:          "mage_blink",
				Name:        "Blink",
				Description: "Teleport short distances",
				Category:    CategoryDefensive,
				MaxRank:     3,
				Bonuses:     StatBonuses{Speed: 0.1, Mana: 10},
			},
			{
				ID:            "mage_mirror_image",
				Name:          "Mirror Image",
				Description:   "Create decoys",
				Category:      CategoryDefensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"mage_blink"},
				Bonuses:       StatBonuses{Mana: 20, Dexterity: 3},
			},
			{
				ID:            "mage_counterspell",
				Name:          "Counterspell",
				Description:   "Interrupt enemy spells",
				Category:      CategoryDefensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"mage_spell_resistance"},
				Bonuses:       StatBonuses{MagicDefense: 5, Intelligence: 2},
			},
			{
				ID:            "mage_temporal_shield",
				Name:          "Temporal Shield",
				Description:   "Time-based protection",
				Category:      CategoryDefensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"mage_arcane_barrier"},
				Bonuses:       StatBonuses{MagicDefense: 6, Mana: 30},
			},
			{
				ID:            "mage_phase_shift",
				Name:          "Phase Shift",
				Description:   "Become incorporeal",
				Category:      CategoryDefensive,
				MaxRank:       1,
				Prerequisites: []TalentID{"mage_mirror_image"},
				Bonuses:       StatBonuses{Speed: 0.2, Mana: 40},
			},
			{
				ID:            "mage_invulnerability",
				Name:          "Invulnerability",
				Description:   "Brief complete immunity",
				Category:      CategoryDefensive,
				MaxRank:       1,
				Prerequisites: []TalentID{"mage_temporal_shield", "mage_counterspell"},
				Bonuses:       StatBonuses{MagicDefense: 10, Defense: 10, Mana: 50},
			},
		},
		Utility: []TalentDefinition{
			{
				ID:          "mage_meditation",
				Name:        "Meditation",
				Description: "Faster mana regeneration",
				Category:    CategoryUtility,
				MaxRank:     5,
				Bonuses:     StatBonuses{Mana: 20, Wisdom: 2},
			},
			{
				ID:          "mage_arcane_intellect",
				Name:        "Arcane Intellect",
				Description: "Boost intelligence",
				Category:    CategoryUtility,
				MaxRank:     5,
				Bonuses:     StatBonuses{Intelligence: 3, Mana: 15},
			},
			{
				ID:            "mage_mana_efficiency",
				Name:          "Mana Efficiency",
				Description:   "Reduced spell costs",
				Category:      CategoryUtility,
				MaxRank:       5,
				Prerequisites: []TalentID{"mage_meditation"},
				Bonuses:       StatBonuses{Mana: 25, Wisdom: 3},
			},
			{
				ID:          "mage_teleport",
				Name:        "Teleport",
				Description: "Long-distance travel",
				Category:    CategoryUtility,
				MaxRank:     3,
				Bonuses:     StatBonuses{Mana: 30, Intelligence: 2},
			},
			{
				ID:            "mage_portal",
				Name:          "Portal",
				Description:   "Create portals for party",
				Category:      CategoryUtility,
				MaxRank:       3,
				Prerequisites: []TalentID{"mage_teleport"},
				Bonuses:       StatBonuses{Mana: 35, Charisma: 3},
			},
			{
				ID:          "mage_conjure_food",
				Name:        "Conjure Food",
				Description: "Create food and water",
				Category:    CategoryUtility,
				MaxRank:     5,
				Bonuses:     StatBonuses{Mana: 10, Wisdom: 1},
			},
			{
				ID:            "mage_detect_magic",
				Name:          "Detect Magic",
				Description:   "Sense magical items",
				Category:      CategoryUtility,
				MaxRank:       3,
				Prerequisites: []TalentID{"mage_arcane_intellect"},
				Bonuses:       StatBonuses{Wisdom: 4, Intelligence: 2},
			},
			{
				ID:            "mage_enchanting",
				Name:          "Enchanting",
				Description:   "Imbue items with magic",
				Category:      CategoryUtility,
				MaxRank:       5,
				Prerequisites: []TalentID{"mage_detect_magic"},
				Bonuses:       StatBonuses{Intelligence: 4, Wisdom: 3},
			},
			{
				ID:            "mage_familiar",
				Name:          "Summon Familiar",
				Description:   "Magical companion",
				Category:      CategoryUtility,
				MaxRank:       3,
				Prerequisites: []TalentID{"mage_conjure_food"},
				Bonuses:       StatBonuses{Charisma: 4, Mana: 20},
			},
			{
				ID:            "mage_omniscience",
				Name:          "Omniscience",
				Description:   "Master of all knowledge",
				Category:      CategoryUtility,
				MaxRank:       5,
				Prerequisites: []TalentID{"mage_enchanting", "mage_portal"},
				Bonuses:       StatBonuses{Intelligence: 6, Wisdom: 6, Mana: 40},
			},
		},
	}
}

// initializeTalentTrees creates talent trees for all base classes
func (m *Manager) initializeTalentTrees() {
	m.talentTrees[ClassWarrior] = createWarriorTalentTree()
	m.talentTrees[ClassMage] = createMageTalentTree()
	m.talentTrees[ClassRogue] = createRogueTalentTree()
	m.talentTrees[ClassCleric] = createClericTalentTree()
	m.talentTrees[ClassBerserker] = createBerserkerTalentTree()
	m.talentTrees[ClassPaladin] = createPaladinTalentTree()
	m.talentTrees[ClassKnight] = createKnightTalentTree()
	m.talentTrees[ClassAssassin] = createAssassinTalentTree()
	m.talentTrees[ClassRanger] = createRangerTalentTree()
	m.talentTrees[ClassNinja] = createNinjaTalentTree()
	m.talentTrees[ClassElementalist] = createElementalistTalentTree()
	m.talentTrees[ClassNecromancer] = createNecromancerTalentTree()
	m.talentTrees[ClassEnchanter] = createEnchanterTalentTree()
	m.talentTrees[ClassBard] = createBardTalentTree()
	m.talentTrees[ClassDruid] = createDruidTalentTree()
}

func createRogueTalentTree() *TalentTree {
	return &TalentTree{
		Name:    "Rogue Talents",
		ClassID: ClassRogue,
		Offensive: []TalentDefinition{
			{
				ID:          "rogue_backstab",
				Name:        "Backstab",
				Description: "Devastating attacks from behind",
				Category:    CategoryOffensive,
				MaxRank:     5,
				Bonuses:     StatBonuses{Dexterity: 3, CritDamage: 0.1},
			},
			{
				ID:          "rogue_poison",
				Name:        "Poison",
				Description: "Apply deadly toxins",
				Category:    CategoryOffensive,
				MaxRank:     5,
				Bonuses:     StatBonuses{Dexterity: 2, Intelligence: 1},
			},
			{
				ID:            "rogue_ambush",
				Name:          "Ambush",
				Description:   "Enhanced opening strike",
				Category:      CategoryOffensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"rogue_backstab"},
				Bonuses:       StatBonuses{Dexterity: 4, CritChance: 0.05},
			},
			{
				ID:          "rogue_deadly_precision",
				Name:        "Deadly Precision",
				Description: "Find vital weak points",
				Category:    CategoryOffensive,
				MaxRank:     5,
				Bonuses:     StatBonuses{CritChance: 0.03, Dexterity: 2},
			},
			{
				ID:            "rogue_eviscerate",
				Name:          "Eviscerate",
				Description:   "Finishing move with critical hits",
				Category:      CategoryOffensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"rogue_deadly_precision"},
				Bonuses:       StatBonuses{CritDamage: 0.2, Dexterity: 3},
			},
			{
				ID:            "rogue_hemorrhage",
				Name:          "Hemorrhage",
				Description:   "Bleeding damage over time",
				Category:      CategoryOffensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"rogue_poison"},
				Bonuses:       StatBonuses{Dexterity: 3, Intelligence: 2},
			},
			{
				ID:            "rogue_shadowstrike",
				Name:          "Shadowstrike",
				Description:   "Teleport and strike",
				Category:      CategoryOffensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"rogue_ambush"},
				Bonuses:       StatBonuses{Dexterity: 5, CritDamage: 0.15, Speed: 0.1},
			},
			{
				ID:            "rogue_kidney_shot",
				Name:          "Kidney Shot",
				Description:   "Stun enemies with precision",
				Category:      CategoryOffensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"rogue_deadly_precision"},
				Bonuses:       StatBonuses{Dexterity: 4},
			},
			{
				ID:            "rogue_vendetta",
				Name:          "Vendetta",
				Description:   "Mark target for death",
				Category:      CategoryOffensive,
				MaxRank:       1,
				Prerequisites: []TalentID{"rogue_eviscerate"},
				Bonuses:       StatBonuses{CritDamage: 0.5, CritChance: 0.1},
			},
			{
				ID:            "rogue_master_assassin",
				Name:          "Master Assassin",
				Description:   "Ultimate killing technique",
				Category:      CategoryOffensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"rogue_shadowstrike", "rogue_vendetta"},
				Bonuses:       StatBonuses{Dexterity: 6, CritDamage: 0.25, CritChance: 0.08},
			},
		},
		Defensive: []TalentDefinition{
			{
				ID:          "rogue_evasion",
				Name:        "Evasion",
				Description: "Dodge incoming attacks",
				Category:    CategoryDefensive,
				MaxRank:     5,
				Bonuses:     StatBonuses{Dexterity: 2, Speed: 0.05},
			},
			{
				ID:          "rogue_feint",
				Name:        "Feint",
				Description: "Reduce threat and damage taken",
				Category:    CategoryDefensive,
				MaxRank:     5,
				Bonuses:     StatBonuses{Dexterity: 2, Defense: 2},
			},
			{
				ID:            "rogue_cloak_of_shadows",
				Name:          "Cloak of Shadows",
				Description:   "Remove harmful effects",
				Category:      CategoryDefensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"rogue_evasion"},
				Bonuses:       StatBonuses{MagicDefense: 5, Dexterity: 3},
			},
			{
				ID:          "rogue_combat_reflexes",
				Name:        "Combat Reflexes",
				Description: "Lightning-fast reactions",
				Category:    CategoryDefensive,
				MaxRank:     5,
				Bonuses:     StatBonuses{Dexterity: 3, Defense: 1},
			},
			{
				ID:            "rogue_preparation",
				Name:          "Preparation",
				Description:   "Reset cooldowns",
				Category:      CategoryDefensive,
				MaxRank:       1,
				Prerequisites: []TalentID{"rogue_combat_reflexes"},
				Bonuses:       StatBonuses{Stamina: 30, Dexterity: 4},
			},
			{
				ID:            "rogue_cheat_death",
				Name:          "Cheat Death",
				Description:   "Survive lethal damage",
				Category:      CategoryDefensive,
				MaxRank:       1,
				Prerequisites: []TalentID{"rogue_cloak_of_shadows"},
				Bonuses:       StatBonuses{Health: 50, Dexterity: 5},
			},
			{
				ID:            "rogue_smoke_bomb",
				Name:          "Smoke Bomb",
				Description:   "Create concealing cloud",
				Category:      CategoryDefensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"rogue_feint"},
				Bonuses:       StatBonuses{Defense: 4, Dexterity: 2},
			},
			{
				ID:            "rogue_riposte",
				Name:          "Riposte",
				Description:   "Counter attacks",
				Category:      CategoryDefensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"rogue_combat_reflexes"},
				Bonuses:       StatBonuses{Dexterity: 4, Defense: 3},
			},
			{
				ID:            "rogue_vanish",
				Name:          "Vanish",
				Description:   "Disappear from combat",
				Category:      CategoryDefensive,
				MaxRank:       1,
				Prerequisites: []TalentID{"rogue_smoke_bomb"},
				Bonuses:       StatBonuses{Speed: 0.2, Dexterity: 6},
			},
			{
				ID:            "rogue_immortal_shadow",
				Name:          "Immortal Shadow",
				Description:   "Unmatched survivability",
				Category:      CategoryDefensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"rogue_cheat_death", "rogue_vanish"},
				Bonuses:       StatBonuses{Health: 60, Defense: 6, Dexterity: 5},
			},
		},
		Utility: []TalentDefinition{
			{
				ID:          "rogue_stealth",
				Name:        "Stealth",
				Description: "Enhanced invisibility",
				Category:    CategoryUtility,
				MaxRank:     5,
				Bonuses:     StatBonuses{Dexterity: 2, Speed: 0.05},
			},
			{
				ID:          "rogue_lockpicking",
				Name:        "Lockpicking",
				Description: "Open locks and chests",
				Category:    CategoryUtility,
				MaxRank:     5,
				Bonuses:     StatBonuses{Dexterity: 3},
			},
			{
				ID:            "rogue_sap",
				Name:          "Sap",
				Description:   "Incapacitate enemies",
				Category:      CategoryUtility,
				MaxRank:       3,
				Prerequisites: []TalentID{"rogue_stealth"},
				Bonuses:       StatBonuses{Dexterity: 3, Intelligence: 2},
			},
			{
				ID:            "rogue_pickpocket",
				Name:          "Pickpocket",
				Description:   "Steal from enemies",
				Category:      CategoryUtility,
				MaxRank:       5,
				Prerequisites: []TalentID{"rogue_lockpicking"},
				Bonuses:       StatBonuses{Dexterity: 4, Charisma: 2},
			},
			{
				ID:          "rogue_detect_traps",
				Name:        "Detect Traps",
				Description: "Sense hidden dangers",
				Category:    CategoryUtility,
				MaxRank:     5,
				Bonuses:     StatBonuses{Wisdom: 3, Dexterity: 1},
			},
			{
				ID:            "rogue_disarm_trap",
				Name:          "Disarm Trap",
				Description:   "Safely disable traps",
				Category:      CategoryUtility,
				MaxRank:       5,
				Prerequisites: []TalentID{"rogue_detect_traps"},
				Bonuses:       StatBonuses{Dexterity: 4, Intelligence: 2},
			},
			{
				ID:            "rogue_distract",
				Name:          "Distract",
				Description:   "Divert enemy attention",
				Category:      CategoryUtility,
				MaxRank:       3,
				Prerequisites: []TalentID{"rogue_sap"},
				Bonuses:       StatBonuses{Charisma: 4, Dexterity: 2},
			},
			{
				ID:          "rogue_sprint",
				Name:        "Sprint",
				Description: "Burst of speed",
				Category:    CategoryUtility,
				MaxRank:     5,
				Bonuses:     StatBonuses{Speed: 0.1, Stamina: 15},
			},
			{
				ID:            "rogue_shadowstep",
				Name:          "Shadowstep",
				Description:   "Teleport to target",
				Category:      CategoryUtility,
				MaxRank:       3,
				Prerequisites: []TalentID{"rogue_sprint"},
				Bonuses:       StatBonuses{Speed: 0.15, Dexterity: 3},
			},
			{
				ID:            "rogue_master_of_shadows",
				Name:          "Master of Shadows",
				Description:   "Ultimate stealth mastery",
				Category:      CategoryUtility,
				MaxRank:       5,
				Prerequisites: []TalentID{"rogue_distract", "rogue_shadowstep"},
				Bonuses:       StatBonuses{Dexterity: 6, Speed: 0.2, Charisma: 4},
			},
		},
	}
}

func createClericTalentTree() *TalentTree {
	return &TalentTree{
		Name:    "Cleric Talents",
		ClassID: ClassCleric,
		Offensive: []TalentDefinition{
			{
				ID:          "cleric_holy_smite",
				Name:        "Holy Smite",
				Description: "Divine damage to enemies",
				Category:    CategoryOffensive,
				MaxRank:     5,
				Bonuses:     StatBonuses{Wisdom: 3, Intelligence: 1},
			},
			{
				ID:          "cleric_turn_undead",
				Name:        "Turn Undead",
				Description: "Repel undead creatures",
				Category:    CategoryOffensive,
				MaxRank:     5,
				Bonuses:     StatBonuses{Wisdom: 3, Charisma: 2},
			},
			{
				ID:            "cleric_divine_wrath",
				Name:          "Divine Wrath",
				Description:   "Channel divine fury",
				Category:      CategoryOffensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"cleric_holy_smite"},
				Bonuses:       StatBonuses{Wisdom: 4, CritDamage: 0.1},
			},
			{
				ID:          "cleric_plague",
				Name:        "Plague",
				Description: "Disease spreading to enemies",
				Category:    CategoryOffensive,
				MaxRank:     3,
				Bonuses:     StatBonuses{Wisdom: 2, Intelligence: 3},
			},
			{
				ID:            "cleric_judgment",
				Name:          "Judgment",
				Description:   "Divine punishment",
				Category:      CategoryOffensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"cleric_divine_wrath"},
				Bonuses:       StatBonuses{Wisdom: 5, CritDamage: 0.15},
			},
			{
				ID:            "cleric_exorcism",
				Name:          "Exorcism",
				Description:   "Banish demonic entities",
				Category:      CategoryOffensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"cleric_turn_undead"},
				Bonuses:       StatBonuses{Wisdom: 4, Charisma: 3},
			},
			{
				ID:            "cleric_holy_fire",
				Name:          "Holy Fire",
				Description:   "Purifying flames",
				Category:      CategoryOffensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"cleric_divine_wrath"},
				Bonuses:       StatBonuses{Wisdom: 4, Intelligence: 2},
			},
			{
				ID:            "cleric_divine_punishment",
				Name:          "Divine Punishment",
				Description:   "Ultimate holy attack",
				Category:      CategoryOffensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"cleric_judgment"},
				Bonuses:       StatBonuses{Wisdom: 6, CritDamage: 0.2},
			},
			{
				ID:            "cleric_smite_evil",
				Name:          "Smite Evil",
				Description:   "Devastating blow to evil",
				Category:      CategoryOffensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"cleric_exorcism"},
				Bonuses:       StatBonuses{Wisdom: 5, Charisma: 4},
			},
			{
				ID:            "cleric_avatar_of_light",
				Name:          "Avatar of Light",
				Description:   "Become divine instrument",
				Category:      CategoryOffensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"cleric_divine_punishment", "cleric_smite_evil"},
				Bonuses:       StatBonuses{Wisdom: 8, Intelligence: 4, Charisma: 4},
			},
		},
		Defensive: []TalentDefinition{
			{
				ID:          "cleric_divine_shield",
				Name:        "Divine Shield",
				Description: "Holy protective barrier",
				Category:    CategoryDefensive,
				MaxRank:     5,
				Bonuses:     StatBonuses{MagicDefense: 3, Wisdom: 2},
			},
			{
				ID:          "cleric_fortitude_buff",
				Name:        "Fortitude",
				Description: "Increase stamina",
				Category:    CategoryDefensive,
				MaxRank:     5,
				Bonuses:     StatBonuses{Health: 20, Stamina: 15},
			},
			{
				ID:            "cleric_divine_protection",
				Name:          "Divine Protection",
				Description:   "Enhanced holy defense",
				Category:      CategoryDefensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"cleric_divine_shield"},
				Bonuses:       StatBonuses{MagicDefense: 5, Defense: 3},
			},
			{
				ID:            "cleric_sanctuary",
				Name:          "Sanctuary",
				Description:   "Zone of safety",
				Category:      CategoryDefensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"cleric_divine_protection"},
				Bonuses:       StatBonuses{MagicDefense: 6, Health: 30},
			},
			{
				ID:            "cleric_stoneskin",
				Name:          "Stoneskin",
				Description:   "Rock-hard defense",
				Category:      CategoryDefensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"cleric_fortitude_buff"},
				Bonuses:       StatBonuses{Defense: 5, Health: 25},
			},
			{
				ID:            "cleric_guardian_spirit",
				Name:          "Guardian Spirit",
				Description:   "Prevent death",
				Category:      CategoryDefensive,
				MaxRank:       1,
				Prerequisites: []TalentID{"cleric_sanctuary"},
				Bonuses:       StatBonuses{Health: 100, Wisdom: 5},
			},
			{
				ID:            "cleric_power_word_shield",
				Name:          "Power Word: Shield",
				Description:   "Instant damage absorption",
				Category:      CategoryDefensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"cleric_divine_protection"},
				Bonuses:       StatBonuses{MagicDefense: 4, Mana: 20},
			},
			{
				ID:            "cleric_divine_aegis",
				Name:          "Divine Aegis",
				Description:   "Shields from critical hits",
				Category:      CategoryDefensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"cleric_power_word_shield"},
				Bonuses:       StatBonuses{MagicDefense: 5, Defense: 4},
			},
			{
				ID:            "cleric_martyrdom",
				Name:          "Martyrdom",
				Description:   "Redirect damage to self",
				Category:      CategoryDefensive,
				MaxRank:       3,
				Prerequisites: []TalentID{"cleric_stoneskin"},
				Bonuses:       StatBonuses{Health: 50, Charisma: 5},
			},
			{
				ID:            "cleric_unbreakable_faith",
				Name:          "Unbreakable Faith",
				Description:   "Ultimate divine defense",
				Category:      CategoryDefensive,
				MaxRank:       5,
				Prerequisites: []TalentID{"cleric_guardian_spirit", "cleric_divine_aegis"},
				Bonuses:       StatBonuses{Health: 80, Defense: 8, MagicDefense: 8},
			},
		},
		Utility: []TalentDefinition{
			{
				ID:          "cleric_heal",
				Name:        "Heal",
				Description: "Restore health",
				Category:    CategoryUtility,
				MaxRank:     5,
				Bonuses:     StatBonuses{Wisdom: 3, Mana: 15},
			},
			{
				ID:          "cleric_renew",
				Name:        "Renew",
				Description: "Healing over time",
				Category:    CategoryUtility,
				MaxRank:     5,
				Bonuses:     StatBonuses{Wisdom: 3, Mana: 10},
			},
			{
				ID:            "cleric_prayer_of_healing",
				Name:          "Prayer of Healing",
				Description:   "Group heal",
				Category:      CategoryUtility,
				MaxRank:       5,
				Prerequisites: []TalentID{"cleric_heal"},
				Bonuses:       StatBonuses{Wisdom: 4, Charisma: 2, Mana: 20},
			},
			{
				ID:          "cleric_flash_heal",
				Name:        "Flash Heal",
				Description: "Quick emergency heal",
				Category:    CategoryUtility,
				MaxRank:     5,
				Bonuses:     StatBonuses{Wisdom: 2, Mana: 20},
			},
			{
				ID:            "cleric_resurrection",
				Name:          "Resurrection",
				Description:   "Revive fallen allies",
				Category:      CategoryUtility,
				MaxRank:       3,
				Prerequisites: []TalentID{"cleric_flash_heal"},
				Bonuses:       StatBonuses{Wisdom: 5, Mana: 40},
			},
			{
				ID:          "cleric_cure_disease",
				Name:        "Cure Disease",
				Description: "Remove ailments",
				Category:    CategoryUtility,
				MaxRank:     5,
				Bonuses:     StatBonuses{Wisdom: 2, Intelligence: 2},
			},
			{
				ID:            "cleric_dispel_magic",
				Name:          "Dispel Magic",
				Description:   "Remove harmful effects",
				Category:      CategoryUtility,
				MaxRank:       5,
				Prerequisites: []TalentID{"cleric_cure_disease"},
				Bonuses:       StatBonuses{Wisdom: 3, Intelligence: 3},
			},
			{
				ID:          "cleric_blessing",
				Name:        "Blessing",
				Description: "Empower allies",
				Category:    CategoryUtility,
				MaxRank:     5,
				Bonuses:     StatBonuses{Charisma: 4, Wisdom: 2},
			},
			{
				ID:            "cleric_divine_intervention",
				Name:          "Divine Intervention",
				Description:   "Call upon deity",
				Category:      CategoryUtility,
				MaxRank:       1,
				Prerequisites: []TalentID{"cleric_resurrection"},
				Bonuses:       StatBonuses{Wisdom: 10, Mana: 50},
			},
			{
				ID:            "cleric_miracle",
				Name:          "Miracle",
				Description:   "Divine power unlimited",
				Category:      CategoryUtility,
				MaxRank:       5,
				Prerequisites: []TalentID{"cleric_divine_intervention", "cleric_prayer_of_healing"},
				Bonuses:       StatBonuses{Wisdom: 8, Charisma: 6, Mana: 60},
			},
		},
	}
}
