// Package engine provides terrain interaction component functionality.
// This file implements TerrainInteractionComponent which tracks visual effects
// generated by vehicle-terrain interactions (water splash, sand trails, etc.).
//
// Phase 21.2: Advanced Vehicle Features - Terrain Interaction
package engine

import "github.com/opd-ai/venture/pkg/procgen/terrain"

// TerrainInteractionComponent stores active terrain effects.
// This component tracks particle effects and visual trails generated
// by vehicle movement across different terrain types.
type TerrainInteractionComponent struct {
	// CurrentTerrainType is the terrain the vehicle is currently on
	CurrentTerrainType terrain.TileType

	// EffectIntensity controls particle spawn rate (0.0 to 1.0)
	// Scales with vehicle speed
	EffectIntensity float64

	// ActiveEffects tracks currently active particle effect IDs
	ActiveEffects []uint64

	// TrailLength determines how long visual trails persist (seconds)
	TrailLength float64

	// TrailFadeTime is time for trail to fade after creation (seconds)
	TrailFadeTime float64

	// LastEffectTime tracks when last effect was spawned
	LastEffectTime float64

	// EffectSpawnInterval minimum time between effect spawns (seconds)
	EffectSpawnInterval float64
}

// Type returns the component type identifier.
func (t *TerrainInteractionComponent) Type() string {
	return "terrain_interaction"
}

// NewTerrainInteractionComponent creates a terrain interaction component.
func NewTerrainInteractionComponent() *TerrainInteractionComponent {
	return &TerrainInteractionComponent{
		CurrentTerrainType:  terrain.TileFloor,
		EffectIntensity:     1.0,
		ActiveEffects:       make([]uint64, 0),
		TrailLength:         2.0,
		TrailFadeTime:       1.0,
		LastEffectTime:      0.0,
		EffectSpawnInterval: 0.1, // 10 effects per second max
	}
}

// UpdateTerrainType updates current terrain and resets effect tracking.
func (t *TerrainInteractionComponent) UpdateTerrainType(terrainType terrain.TileType) {
	if t.CurrentTerrainType != terrainType {
		t.CurrentTerrainType = terrainType
		// Clear effects when terrain changes
		t.ActiveEffects = t.ActiveEffects[:0]
	}
}

// CanSpawnEffect checks if enough time has passed since last effect.
func (t *TerrainInteractionComponent) CanSpawnEffect(currentTime float64) bool {
	return (currentTime - t.LastEffectTime) >= t.EffectSpawnInterval
}

// RecordEffect adds an effect ID to active effects and updates spawn time.
func (t *TerrainInteractionComponent) RecordEffect(effectID uint64, currentTime float64) {
	t.ActiveEffects = append(t.ActiveEffects, effectID)
	t.LastEffectTime = currentTime
}

// ClearOldEffects removes effect IDs that are no longer needed.
// Should be called periodically to prevent unbounded growth.
func (t *TerrainInteractionComponent) ClearOldEffects() {
	if len(t.ActiveEffects) > 100 {
		// Keep only most recent 50 effects
		t.ActiveEffects = t.ActiveEffects[len(t.ActiveEffects)-50:]
	}
}

// GetEffectColorForTerrain returns particle color based on terrain type.
func GetEffectColorForTerrain(terrainType terrain.TileType) (r, g, b, a uint8) {
	switch terrainType {
	case terrain.TileWaterShallow, terrain.TileWaterDeep:
		// Blue water splash
		return 100, 150, 255, 200

	case terrain.TileTree:
		// Brown/green debris
		return 139, 90, 43, 180

	default:
		// Gray dust/dirt for most surfaces
		return 180, 180, 160, 150
	}
}

// GetEffectTypeForTerrain returns effect style based on terrain.
func GetEffectTypeForTerrain(terrainType terrain.TileType) string {
	switch terrainType {
	case terrain.TileWaterShallow:
		return "splash_small"
	case terrain.TileWaterDeep:
		return "splash_large"
	case terrain.TileTree:
		return "leaves"
	default:
		return "dust"
	}
}
