package features

import "time"

// RegisterAdvancedFeatures adds all advanced system features to the registry
func RegisterAdvancedFeatures(r *FeatureRegistry) {
	// Quests
	r.Register(&Feature{
		ID:                   "quests.accept",
		Name:                 "Accept Quest",
		Category:             CategoryCore,
		Description:          "Accept quests from NPCs",
		Accessible:           true,
		AccessibilityTime:    5 * time.Minute,
		AccessibilityPath:    "Talk to NPC (F key), accept quest",
		HasTutorial:          true,
		TutorialLocation:     "First NPC interaction",
		TutorialCompleteness: 1.0,
		IntegratedSystems:    []string{"dialog", "objectives", "ui"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "quests.track",
		Name:                 "Quest Tracking",
		Category:             CategoryCore,
		Description:          "Track active quest objectives",
		Accessible:           true,
		AccessibilityTime:    6 * time.Minute,
		AccessibilityPath:    "Accept quest, open quest log (Q key)",
		HasTutorial:          true,
		TutorialLocation:     "Quest UI tutorial",
		TutorialCompleteness: 0.9,
		IntegratedSystems:    []string{"objectives", "ui", "map"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "quests.complete",
		Name:                 "Complete Quest",
		Category:             CategoryCore,
		Description:          "Complete quest objectives",
		Accessible:           true,
		AccessibilityTime:    15 * time.Minute,
		AccessibilityPath:    "Complete quest objectives, return to NPC",
		HasTutorial:          true,
		TutorialLocation:     "Quest completion notification",
		TutorialCompleteness: 0.9,
		IntegratedSystems:    []string{"rewards", "progression", "reputation"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "quests.turnin",
		Name:                 "Turn In Quest",
		Category:             CategoryCore,
		Description:          "Turn in completed quests for rewards",
		Accessible:           true,
		AccessibilityTime:    15 * time.Minute,
		AccessibilityPath:    "Complete quest, talk to NPC",
		HasTutorial:          true,
		TutorialLocation:     "Quest turn-in dialog",
		TutorialCompleteness: 0.9,
		IntegratedSystems:    []string{"dialog", "rewards", "progression"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	// Crafting
	r.Register(&Feature{
		ID:                   "crafting.gather",
		Name:                 "Gather Materials",
		Category:             CategoryEconomy,
		Description:          "Collect crafting materials from world",
		Accessible:           true,
		AccessibilityTime:    10 * time.Minute,
		AccessibilityPath:    "Find resources in dungeon, press E to collect",
		HasTutorial:          true,
		TutorialLocation:     "Resource collection tutorial",
		TutorialCompleteness: 0.8,
		IntegratedSystems:    []string{"interaction", "inventory", "world"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "crafting.recipes",
		Name:                 "Use Recipes",
		Category:             CategoryEconomy,
		Description:          "Learn and use crafting recipes",
		Accessible:           true,
		AccessibilityTime:    20 * time.Minute,
		AccessibilityPath:    "Find recipe book, open crafting station",
		HasTutorial:          true,
		TutorialLocation:     "Crafting station UI",
		TutorialCompleteness: 0.9,
		IntegratedSystems:    []string{"stations", "items", "progression"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "crafting.create",
		Name:                 "Craft Items",
		Category:             CategoryEconomy,
		Description:          "Create items at crafting stations",
		Accessible:           true,
		AccessibilityTime:    25 * time.Minute,
		AccessibilityPath:    "Gather materials, use recipe at station",
		HasTutorial:          true,
		TutorialLocation:     "Crafting UI tutorial",
		TutorialCompleteness: 0.9,
		IntegratedSystems:    []string{"stations", "materials", "inventory"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	// Death/Revival
	r.Register(&Feature{
		ID:                   "death.respawn",
		Name:                 "Respawn",
		Category:             CategoryCore,
		Description:          "Respawn after death",
		Accessible:           true,
		AccessibilityTime:    5 * time.Minute,
		AccessibilityPath:    "Die in combat, click respawn button",
		HasTutorial:          true,
		TutorialLocation:     "Death screen",
		TutorialCompleteness: 1.0,
		IntegratedSystems:    []string{"health", "spawn", "penalties"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "death.corpse",
		Name:                 "Corpse Recovery",
		Category:             CategoryCore,
		Description:          "Recover items from corpse",
		Accessible:           true,
		AccessibilityTime:    10 * time.Minute,
		AccessibilityPath:    "Die, respawn, travel to corpse, loot",
		HasTutorial:          true,
		TutorialLocation:     "Death system tutorial",
		TutorialCompleteness: 0.8,
		IntegratedSystems:    []string{"loot", "world", "navigation"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "death.penalties",
		Name:                 "Death Penalties",
		Category:             CategoryCore,
		Description:          "XP/gold loss on death",
		Accessible:           true,
		AccessibilityTime:    5 * time.Minute,
		AccessibilityPath:    "Die in combat, observe penalties",
		HasTutorial:          true,
		TutorialLocation:     "Death screen tooltip",
		TutorialCompleteness: 0.8,
		IntegratedSystems:    []string{"progression", "economy", "difficulty"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	// Vehicles (V4.0)
	r.Register(&Feature{
		ID:                   "vehicles.mount",
		Name:                 "Mount Vehicle",
		Category:             CategoryVehicles,
		Description:          "Mount and ride vehicles/mounts",
		Accessible:           true,
		AccessibilityTime:    20 * time.Minute,
		AccessibilityPath:    "Find vehicle, press M to mount",
		HasTutorial:          true,
		TutorialLocation:     "Vehicle tutorial",
		TutorialCompleteness: 0.9,
		IntegratedSystems:    []string{"movement", "physics", "speed"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "vehicles.combat",
		Name:                 "Vehicle Combat",
		Category:             CategoryVehicles,
		Description:          "Fight while mounted",
		Accessible:           true,
		AccessibilityTime:    25 * time.Minute,
		AccessibilityPath:    "Mount vehicle, engage combat",
		HasTutorial:          true,
		TutorialLocation:     "Vehicle combat tooltip",
		TutorialCompleteness: 0.8,
		IntegratedSystems:    []string{"combat", "ramming", "weapons"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "vehicles.upgrades",
		Name:                 "Vehicle Upgrades",
		Category:             CategoryVehicles,
		Description:          "Upgrade vehicle speed, armor, weapons",
		Accessible:           true,
		AccessibilityTime:    30 * time.Minute,
		AccessibilityPath:    "Find upgrade items, apply at station",
		HasTutorial:          true,
		TutorialLocation:     "Upgrade UI help text",
		TutorialCompleteness: 0.7,
		IntegratedSystems:    []string{"items", "crafting", "stats"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	// Companions (V4.0)
	r.Register(&Feature{
		ID:                   "companions.tame",
		Name:                 "Tame Companion",
		Category:             CategoryAdvanced,
		Description:          "Tame pets and companions",
		Accessible:           true,
		AccessibilityTime:    25 * time.Minute,
		AccessibilityPath:    "Find tameable creature, use taming item",
		HasTutorial:          true,
		TutorialLocation:     "Companion system tutorial",
		TutorialCompleteness: 0.8,
		IntegratedSystems:    []string{"ai", "loyalty", "inventory"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "companions.commands",
		Name:                 "Companion Commands",
		Category:             CategoryAdvanced,
		Description:          "Give commands (follow, attack, defend)",
		Accessible:           true,
		AccessibilityTime:    30 * time.Minute,
		AccessibilityPath:    "Tame companion, open command menu",
		HasTutorial:          true,
		TutorialLocation:     "Companion UI tooltips",
		TutorialCompleteness: 0.8,
		IntegratedSystems:    []string{"ai", "combat", "input"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "companions.progression",
		Name:                 "Companion Progression",
		Category:             CategoryAdvanced,
		Description:          "Companions gain XP and level up",
		Accessible:           true,
		AccessibilityTime:    40 * time.Minute,
		AccessibilityPath:    "Use companion in combat, observe XP gain",
		HasTutorial:          true,
		TutorialLocation:     "Companion stats UI",
		TutorialCompleteness: 0.7,
		IntegratedSystems:    []string{"combat", "stats", "progression"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	// Classes (V4.0)
	r.Register(&Feature{
		ID:                   "classes.select",
		Name:                 "Class Selection",
		Category:             CategoryAdvanced,
		Description:          "Choose character class at start",
		Accessible:           true,
		AccessibilityTime:    1 * time.Minute,
		AccessibilityPath:    "Character creation screen",
		HasTutorial:          true,
		TutorialLocation:     "Class selection UI",
		TutorialCompleteness: 1.0,
		IntegratedSystems:    []string{"stats", "abilities", "progression"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "classes.abilities",
		Name:                 "Class Abilities",
		Category:             CategoryAdvanced,
		Description:          "Use class-specific abilities",
		Accessible:           true,
		AccessibilityTime:    10 * time.Minute,
		AccessibilityPath:    "Level up, unlock class ability",
		HasTutorial:          true,
		TutorialLocation:     "Ability unlock notification",
		TutorialCompleteness: 0.9,
		IntegratedSystems:    []string{"combat", "skills", "mana"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "classes.dual",
		Name:                 "Dual-Classing",
		Category:             CategoryAdvanced,
		Description:          "Unlock second class at level 20",
		Accessible:           true,
		AccessibilityTime:    180 * time.Minute,
		AccessibilityPath:    "Reach level 20, visit class trainer",
		HasTutorial:          true,
		TutorialLocation:     "Dual-class UI",
		TutorialCompleteness: 0.8,
		IntegratedSystems:    []string{"progression", "abilities", "stats"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})
}
