package features

import "time"

// RegisterCoreFeatures adds all core gameplay features to the registry
func RegisterCoreFeatures(r *FeatureRegistry) {
	// Movement
	r.Register(&Feature{
		ID:                   "movement.8dir",
		Name:                 "8-Direction Movement",
		Category:             CategoryCore,
		Description:          "WASD movement with 8 directional support",
		Accessible:           true,
		AccessibilityTime:    1 * time.Minute,
		AccessibilityPath:    "Tutorial: press WASD keys",
		HasTutorial:          true,
		TutorialLocation:     "First-time tutorial popup",
		TutorialCompleteness: 1.0,
		IntegratedSystems:    []string{"collision", "viewport", "animation"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "movement.rotation",
		Name:                 "360° Rotation",
		Category:             CategoryCore,
		Description:          "Rotate character facing direction with mouse",
		Accessible:           true,
		AccessibilityTime:    1 * time.Minute,
		AccessibilityPath:    "Tutorial: move mouse cursor",
		HasTutorial:          true,
		TutorialLocation:     "First-time tutorial popup",
		TutorialCompleteness: 1.0,
		IntegratedSystems:    []string{"input", "animation", "combat"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "movement.aim",
		Name:                 "Mouse Aim",
		Category:             CategoryCore,
		Description:          "Aim projectiles and spells with mouse",
		Accessible:           true,
		AccessibilityTime:    2 * time.Minute,
		AccessibilityPath:    "Tutorial: equip bow or spell, aim with mouse",
		HasTutorial:          true,
		TutorialLocation:     "Combat tutorial",
		TutorialCompleteness: 1.0,
		IntegratedSystems:    []string{"combat", "projectile", "input"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	// Combat
	r.Register(&Feature{
		ID:                   "combat.melee",
		Name:                 "Melee Combat",
		Category:             CategoryCombat,
		Description:          "Close-range combat with swords, axes, etc.",
		Accessible:           true,
		AccessibilityTime:    3 * time.Minute,
		AccessibilityPath:    "Tutorial: equip weapon, left-click to attack",
		HasTutorial:          true,
		TutorialLocation:     "Combat tutorial",
		TutorialCompleteness: 1.0,
		IntegratedSystems:    []string{"inventory", "damage", "animation"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "combat.ranged",
		Name:                 "Ranged Combat",
		Category:             CategoryCombat,
		Description:          "Long-range combat with bows, guns, etc.",
		Accessible:           true,
		AccessibilityTime:    5 * time.Minute,
		AccessibilityPath:    "Find bow in dungeon, equip, left-click to shoot",
		HasTutorial:          true,
		TutorialLocation:     "Combat tutorial, weapon tooltips",
		TutorialCompleteness: 1.0,
		IntegratedSystems:    []string{"projectile", "aiming", "damage"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "combat.magic",
		Name:                 "Magic Combat",
		Category:             CategoryCombat,
		Description:          "Cast spells for damage and effects",
		Accessible:           true,
		AccessibilityTime:    8 * time.Minute,
		AccessibilityPath:    "Find spell book, equip spell, cast with hotkey",
		HasTutorial:          true,
		TutorialLocation:     "Magic tutorial, spell tooltips",
		TutorialCompleteness: 1.0,
		IntegratedSystems:    []string{"mana", "spellcasting", "effects"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "combat.status",
		Name:                 "Status Effects",
		Category:             CategoryCombat,
		Description:          "Buffs/debuffs like poison, burn, freeze",
		Accessible:           true,
		AccessibilityTime:    10 * time.Minute,
		AccessibilityPath:    "Get poisoned by enemy or apply buff potion",
		HasTutorial:          true,
		TutorialLocation:     "Status effect tooltips",
		TutorialCompleteness: 0.8,
		IntegratedSystems:    []string{"combat", "items", "visual"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	// Inventory
	r.Register(&Feature{
		ID:                   "inventory.pickup",
		Name:                 "Item Pickup",
		Category:             CategoryCore,
		Description:          "Pick up items from ground",
		Accessible:           true,
		AccessibilityTime:    2 * time.Minute,
		AccessibilityPath:    "Walk over item, press E key",
		HasTutorial:          true,
		TutorialLocation:     "First item pickup prompt",
		TutorialCompleteness: 1.0,
		IntegratedSystems:    []string{"interaction", "loot", "inventory-ui"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "inventory.equip",
		Name:                 "Equipment",
		Category:             CategoryCore,
		Description:          "Equip weapons, armor, accessories",
		Accessible:           true,
		AccessibilityTime:    3 * time.Minute,
		AccessibilityPath:    "Open inventory (I key), click item to equip",
		HasTutorial:          true,
		TutorialLocation:     "Inventory tutorial",
		TutorialCompleteness: 1.0,
		IntegratedSystems:    []string{"stats", "visuals", "combat"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "inventory.use",
		Name:                 "Use Items",
		Category:             CategoryCore,
		Description:          "Use consumables (potions, food)",
		Accessible:           true,
		AccessibilityTime:    4 * time.Minute,
		AccessibilityPath:    "Find potion, press hotkey or right-click in inventory",
		HasTutorial:          true,
		TutorialLocation:     "Consumable tutorial",
		TutorialCompleteness: 1.0,
		IntegratedSystems:    []string{"health", "buffs", "cooldowns"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "inventory.drop",
		Name:                 "Drop Items",
		Category:             CategoryCore,
		Description:          "Drop items from inventory",
		Accessible:           true,
		AccessibilityTime:    5 * time.Minute,
		AccessibilityPath:    "Open inventory, drag item out",
		HasTutorial:          true,
		TutorialLocation:     "Inventory tooltip",
		TutorialCompleteness: 0.8,
		IntegratedSystems:    []string{"world", "loot", "cleanup"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "inventory.trade",
		Name:                 "Trading",
		Category:             CategoryEconomy,
		Description:          "Trade items with other players",
		Accessible:           true,
		AccessibilityTime:    15 * time.Minute,
		AccessibilityPath:    "Meet another player, initiate trade",
		HasTutorial:          true,
		TutorialLocation:     "Trade UI help text",
		TutorialCompleteness: 0.9,
		IntegratedSystems:    []string{"multiplayer", "trust", "ui"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	// Progression
	r.Register(&Feature{
		ID:                   "progression.xp",
		Name:                 "XP Gain",
		Category:             CategoryCore,
		Description:          "Gain experience from combat, quests, crafting",
		Accessible:           true,
		AccessibilityTime:    1 * time.Minute,
		AccessibilityPath:    "Kill first enemy or complete tutorial quest",
		HasTutorial:          true,
		TutorialLocation:     "XP bar tutorial",
		TutorialCompleteness: 1.0,
		IntegratedSystems:    []string{"combat", "quests", "ui"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "progression.leveling",
		Name:                 "Level Up",
		Category:             CategoryCore,
		Description:          "Level up when XP bar fills",
		Accessible:           true,
		AccessibilityTime:    10 * time.Minute,
		AccessibilityPath:    "Gain XP until level 2",
		HasTutorial:          true,
		TutorialLocation:     "Level up notification",
		TutorialCompleteness: 1.0,
		IntegratedSystems:    []string{"stats", "skills", "visual"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "progression.stats",
		Name:                 "Stat Allocation",
		Category:             CategoryCore,
		Description:          "Allocate stat points on level up",
		Accessible:           true,
		AccessibilityTime:    10 * time.Minute,
		AccessibilityPath:    "Level up, open character sheet",
		HasTutorial:          true,
		TutorialLocation:     "Stat allocation UI",
		TutorialCompleteness: 0.9,
		IntegratedSystems:    []string{"character", "stats", "combat"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	// Skills
	r.Register(&Feature{
		ID:                   "skills.unlock",
		Name:                 "Skill Unlock",
		Category:             CategoryCore,
		Description:          "Unlock new skills at certain levels",
		Accessible:           true,
		AccessibilityTime:    15 * time.Minute,
		AccessibilityPath:    "Reach level 5, open skills menu",
		HasTutorial:          true,
		TutorialLocation:     "Skills UI tutorial",
		TutorialCompleteness: 0.9,
		IntegratedSystems:    []string{"progression", "combat", "ui"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "skills.upgrade",
		Name:                 "Skill Upgrade",
		Category:             CategoryCore,
		Description:          "Upgrade existing skills with points",
		Accessible:           true,
		AccessibilityTime:    20 * time.Minute,
		AccessibilityPath:    "Earn skill points, upgrade in skills menu",
		HasTutorial:          true,
		TutorialLocation:     "Skills menu tooltips",
		TutorialCompleteness: 0.8,
		IntegratedSystems:    []string{"progression", "balance", "ui"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})

	r.Register(&Feature{
		ID:                   "skills.use",
		Name:                 "Skill Usage",
		Category:             CategoryCore,
		Description:          "Use skills in combat with hotkeys",
		Accessible:           true,
		AccessibilityTime:    15 * time.Minute,
		AccessibilityPath:    "Assign skill to hotkey, use in combat",
		HasTutorial:          true,
		TutorialLocation:     "Combat tutorial, hotkey UI",
		TutorialCompleteness: 0.9,
		IntegratedSystems:    []string{"input", "combat", "cooldowns"},
		IntegrationCount:     3,
		Implemented:          true,
		Tested:               true,
		Functional:           true,
	})
}
