package imagetest
package main









































































































































































































































































































































































































































































































}	logrus.Infof("Moderation test complete. Images in manager: %d", manager.GetImageCount())	}		logrus.Error("Large image should have been rejected by moderation")	} else {		logrus.Infof("Large image correctly rejected by moderation: %v", err)	if err != nil {	_, err = manager.UploadImage(req)	req.Data = largeData	req.SenderID = 2 // Different sender to avoid rate limit	}		logrus.Fatalf("Failed to create large image: %v", err)	if err != nil {	largeData, err := createTestImage(500, 500, "png")	logrus.Info("Test 2: Uploading large image (should fail moderation)")	// Test 2: Large image (should fail)	}		logrus.Infof("Small image upload succeeded: %s", metadata.ImageID)	} else {		logrus.Errorf("Small image upload failed: %v", err)	if err != nil {	metadata, err := manager.UploadImage(req)	}		Data:     smallData,		Format:   "png",		Channel:  0,		SenderID: 1,	req := &network.ImageUploadRequest{	}		logrus.Fatalf("Failed to create small image: %v", err)	if err != nil {	smallData, err := createTestImage(100, 100, "png")	logrus.Info("Test 1: Uploading small image (should pass moderation)")	// Test 1: Small image (should pass)	})		return nil		logrus.Info("Image approved by moderation")		}			return fmt.Errorf("image too large for moderation test")			logrus.Warn("Image rejected by moderation (too large)")		if len(data) > 50*1024 {		logrus.Infof("Moderation hook called for image %s (size: %d bytes)", metadata.ImageID, len(data))	manager.SetModerationHook(func(metadata *network.ImageMetadata, data []byte) error {	// Set moderation hook that rejects images over 50KB	manager := network.NewImageManager()	logrus.Info("Testing moderation hooks...")func testModeration() {// testModeration tests moderation hook functionality}	logrus.Infof("Note: Rate limit is %v per player", network.ImageRateLimit)	logrus.Info("Rate limit test complete (full 60s test would take too long)")	}		logrus.Errorf("Third upload should have failed with rate limit error, got: %v", err)	} else {		logrus.Info("Third upload correctly blocked by rate limit")	if err == network.ErrRateLimitExceeded {	_, err = manager.UploadImage(req)	logrus.Info("Attempt 3: After 2 seconds (should still fail - 60s limit)")	time.Sleep(2 * time.Second)	logrus.Info("Waiting 2 seconds...")	// Wait and try again	}		logrus.Errorf("Second upload should have failed with rate limit error, got: %v", err)	} else {		logrus.Info("Second upload correctly blocked by rate limit")	if err == network.ErrRateLimitExceeded {	_, err = manager.UploadImage(req)	logrus.Info("Attempt 2: Immediate second upload (should fail - rate limit)")	// Immediate second upload should fail	}		logrus.Infof("First upload succeeded: %s", metadata.ImageID)	} else {		logrus.Errorf("First upload failed: %v", err)	if err != nil {	metadata, err := manager.UploadImage(req)	logrus.Info("Attempt 1: First upload (should succeed)")	// First upload should succeed	}		Data:     data,		Format:   "png",		Channel:  0,		SenderID: senderID,	req := &network.ImageUploadRequest{	}		logrus.Fatalf("Failed to create test image: %v", err)	if err != nil {	data, err := createTestImage(100, 100, "png")	// Create test image	senderID := uint64(1)	manager := network.NewImageManager()	logrus.Info("Testing rate limiting...")func testRateLimit() {// testRateLimit tests upload rate limiting}	}		}			logrus.Infof("Image %d (%s) is still accessible", i+1, imageIDs[i])		} else {			logrus.Errorf("Image %d (%s) should still be accessible: %v", i+1, imageIDs[i], err)		if err != nil {		_, err := manager.GetFullImage(imageIDs[i])	for i := 1; i < 3; i++ {	// Verify remaining images are still accessible	logrus.Infof("Total images expired: %d", expiryCount)	logrus.Infof("Images remaining in manager: %d", manager.GetImageCount())	time.Sleep(100 * time.Millisecond)	manager.OnPlayerDisconnect(1)	// Note: expireImage is not exported, so we simulate by disconnecting the player	logrus.Infof("Manually expiring first image: %s", imageIDs[0])	// Manually expire first image to test callback	time.Sleep(2 * time.Second)	logrus.Info("Waiting 2 seconds before triggering manual expiry...")	// Simulate waiting (in real scenario, images expire after 10 minutes)	logrus.Infof("All images uploaded. Images in manager: %d", manager.GetImageCount())	}		time.Sleep(100 * time.Millisecond)		// Wait between uploads to avoid rate limiting		logrus.Infof("Uploaded image %d: %s (expires at %s)", i+1, metadata.ImageID, metadata.ExpiryTime.Format(time.RFC3339))		imageIDs[i] = metadata.ImageID		}			logrus.Fatalf("Upload failed: %v", err)		if err != nil {		metadata, err := manager.UploadImage(req)		}			Data:     data,			Format:   "png",			Channel:  0,			SenderID: uint64(i + 1),		req := &network.ImageUploadRequest{		}			logrus.Fatalf("Failed to create test image: %v", err)		if err != nil {		data, err := createTestImage(100, 100, "png")	for i := 0; i < 3; i++ {	imageIDs := make([]string, 3)	// Upload multiple images	})		logrus.Infof("Image expired: %s (total expired: %d)", imageID, expiryCount)		expiryCount++	manager.SetExpiryCallback(func(imageID string) {	expiryCount := 0	// Set expiry callback	manager := network.NewImageManager()	logrus.Info("Testing image expiry...")func testExpiry() {// testExpiry tests image expiry functionality}	logrus.Infof("Images in manager: %d", imageCount)	imageCount := manager.GetImageCount()	// For testing, we'll just verify the count	// Find the uploaded image (it gets a new ID after completion)	time.Sleep(100 * time.Millisecond)	// Wait a moment for upload to complete and be stored	logrus.Info("Testing chunked download...")	// Test chunked download	}		}			logrus.Infof("Upload speed: %.2f MB/s", float64(len(data))/(1024*1024)/elapsed.Seconds())			logrus.Infof("Chunked upload complete! Total time: %v", elapsed)			elapsed := time.Since(start)		if complete {		logrus.Debugf("Chunk %d/%d received (%d bytes)", i+1, totalChunks, len(chunkData))		}			logrus.Fatalf("Failed to receive chunk %d: %v", i, err)		if err != nil {		complete, err := manager.ReceiveChunk(chunk)		}			Data:        chunkData,			TotalChunks: totalChunks,			ChunkIndex:  i,			ImageID:     imageID,		chunk := &network.ImageChunk{		chunkData := data[startOffset:endOffset]		}			endOffset = len(data)		if endOffset > len(data) {		endOffset := startOffset + network.MaxChunkSize		startOffset := i * network.MaxChunkSize	for i := 0; i < totalChunks; i++ {	start := time.Now()	// Send chunks	logrus.Infof("Chunked upload started: ImageID=%s", imageID)	}		logrus.Fatalf("Failed to start chunked upload: %v", err)	if err != nil {	imageID, err := manager.StartChunkedUpload(senderID, channel, "png", len(data), totalChunks)	channel := 0	senderID := uint64(1)	// Start chunked upload	logrus.Infof("Image will be split into %d chunks (%d bytes each)", totalChunks, network.MaxChunkSize)	totalChunks := (len(data) + network.MaxChunkSize - 1) / network.MaxChunkSize	// Calculate chunks	logrus.Infof("Created large test image (%dx%d, %d bytes)", largeWidth, largeHeight, len(data))	}		logrus.Fatalf("Failed to create test image: %v", err)	if err != nil {	data, err := createTestImage(largeWidth, largeHeight, "png")	largeHeight := 1024	largeWidth := 1024	// Create large test image	manager := network.NewImageManager()	logrus.Info("Testing chunked transfer...")func testChunkedTransfer() {// testChunkedTransfer tests chunked upload and download}	logrus.Infof("Compression ratio: %.2fx (original: %d bytes, thumbnail: %d bytes)", compressionRatio, len(data), len(thumbnail))	compressionRatio := float64(len(data)) / float64(len(thumbnail))	// Calculate compression ratio	}		logrus.Infof("Thumbnail saved to: %s", thumbPath)	} else {		logrus.Errorf("Failed to save thumbnail: %v", err)	if err := os.WriteFile(thumbPath, thumbnail, 0644); err != nil {	thumbPath := filepath.Join(*outputDir, fmt.Sprintf("thumbnail_%dx%d.jpg", *width, *height))	// Save thumbnail to file	}		logrus.Infof("Thumbnail dimensions: %dx%d", bounds.Dx(), bounds.Dy())		bounds := thumbImg.Bounds()	if err == nil {	thumbImg, err := jpeg.Decode(os.NewFile(0, ""))	// Decode thumbnail to verify dimensions	logrus.Infof("Thumbnail generated in %v (%d bytes)", elapsed, len(thumbnail))	elapsed := time.Since(start)	}		logrus.Fatalf("Thumbnail generation failed: %v", err)	if err != nil {	thumbnail, err := network.GenerateThumbnail(img)	start := time.Now()	// Generate thumbnail	logrus.Infof("Image validated successfully (format: %s)", format)	}		logrus.Fatalf("Image validation failed: %v", err)	if err != nil {	img, format, err := network.ValidateImageData(data, *format)	// Validate and decode	logrus.Infof("Created %s image (%dx%d, %d bytes)", *format, *width, *height, len(data))	}		logrus.Fatalf("Failed to create test image: %v", err)	if err != nil {	data, err := createTestImage(*width, *height, *format)	// Create test image	}		logrus.Fatalf("Failed to create output directory: %v", err)	if err := os.MkdirAll(*outputDir, 0755); err != nil {	// Create output directory	logrus.Info("Testing thumbnail generation...")func testThumbnail() {// testThumbnail tests thumbnail generation}	logrus.Infof("Images stored: %d", manager.GetImageCount())	logrus.Infof("Thumbnails relayed: %d", thumbnailCount)	logrus.Infof("Uploaded %d images in %v (avg: %v per image)", *uploadCount, elapsed, elapsed/time.Duration(*uploadCount))	elapsed := time.Since(start)	}		logrus.Infof("Upload %d: Retrieved full image (%d bytes) and thumbnail (%d bytes)", i+1, len(fullImage), len(thumb))		}			continue			logrus.Errorf("Failed to retrieve thumbnail: %v", err)		if err != nil {		thumb, err := manager.GetThumbnail(metadata.ImageID)		}			logrus.Errorf("Retrieved image size mismatch: expected %d, got %d", metadata.Size, len(fullImage))		if len(fullImage) != metadata.Size {		}			continue			logrus.Errorf("Failed to retrieve full image: %v", err)		if err != nil {		fullImage, err := manager.GetFullImage(metadata.ImageID)		// Verify retrieval		logrus.Infof("Upload %d: Success! ImageID=%s, Size=%d bytes, Thumbnail relayed", i+1, metadata.ImageID, metadata.Size)		}			continue			logrus.Errorf("Upload %d failed: %v", i+1, err)		if err != nil {		metadata, err := manager.UploadImage(req)		}			Data:     data,			Format:   *format,			Channel:  0,			SenderID: uint64(i + 1),		req := &network.ImageUploadRequest{		// Upload image		logrus.Infof("Upload %d: Created %s image (%dx%d, %d bytes)", i+1, *format, *width, *height, len(data))		}			logrus.Fatalf("Failed to create test image %d: %v", i, err)		if err != nil {		data, err := createTestImage(*width, *height, *format)		// Create test image	for i := 0; i < *uploadCount; i++ {	start := time.Now()	})		logrus.Infof("Thumbnail relayed for image %s (size: %d bytes)", metadata.ImageID, len(thumbnail))		thumbnailCount++	manager.SetThumbnailRelayCallback(func(metadata *network.ImageMetadata, thumbnail []byte) {	thumbnailCount := 0	// Set thumbnail relay callback	manager := network.NewImageManager()	logrus.Info("Testing image upload...")func testUpload() {// testUpload tests basic image upload functionality}	return buf, nil	}		return nil, fmt.Errorf("unsupported format: %s", format)	default:		}			return nil, err		if err != nil {		buf, err = os.ReadFile(file.Name())		file.Close()		}			return nil, err		if err := jpeg.Encode(file, img, &jpeg.Options{Quality: 90}); err != nil {		defer os.Remove(file.Name())		}			return nil, err		if err != nil {		file, err := os.CreateTemp("", "test-*.jpg")	case "jpeg":		}			return nil, err		if err != nil {		buf, err = os.ReadFile(file.Name())		file.Close()		}			return nil, err		if err := png.Encode(file, img); err != nil {		defer os.Remove(file.Name())		}			return nil, err		if err != nil {		file, err := os.CreateTemp("", "test-*.png")	case "png":	switch format {	var buf []byte	// Save to buffer	}		}			img.Set(x, y, color.RGBA{R: r, G: g, B: b, A: 255})			b := uint8(128)			g := uint8((y * 255) / height)			r := uint8((x * 255) / width)		for x := 0; x < width; x++ {	for y := 0; y < height; y++ {	// Fill with gradient pattern	img := image.NewRGBA(image.Rect(0, 0, width, height))func createTestImage(width, height int, format string) ([]byte, error) {// createTestImage creates a test image with gradient pattern}	}		os.Exit(1)		flag.Usage()		logrus.Errorf("Unknown test mode: %s", *testMode)	default:		os.Exit(1)		flag.Usage()		logrus.Error("No test mode specified. Use -test flag")	case "":		testModeration()	case "moderation":		testRateLimit()	case "ratelimit":		testExpiry()	case "expiry":		testChunkedTransfer()	case "chunked":		testThumbnail()	case "thumbnail":		testUpload()	case "upload":	switch *testMode {	logrus.Infof("Test mode: %s", *testMode)	logrus.Info("Image Sharing System Test Tool")	}		logrus.SetLevel(logrus.InfoLevel)	} else {		logrus.SetLevel(logrus.DebugLevel)	if *verbose {	// Setup logging	flag.Parse()func main() {)	verbose     = flag.Bool("verbose", false, "Enable verbose logging")	outputDir   = flag.String("output", "./test_images", "Output directory for generated images")	testMode    = flag.String("test", "", "Test mode: upload, thumbnail, chunked, expiry, ratelimit, moderation")	uploadCount = flag.Int("count", 1, "Number of images to upload")	format      = flag.String("format", "png", "Image format (png, jpeg, gif)")	height      = flag.Int("height", 256, "Image height in pixels")	width       = flag.Int("width", 256, "Image width in pixels")var ()	"github.com/sirupsen/logrus"	"github.com/opd-ai/venture/pkg/network"	"time"	"path/filepath"	"os"	"image/png"	"image/jpeg"	"image/color"	"image"	"fmt"	"flag"import (