name: Android Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  GO_VERSION: '1.24.7'
  ANDROID_API_LEVEL: '34'
  ANDROID_BUILD_TOOLS: '34.0.0'
  NDK_VERSION: '26.1.10909125'

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: sdkmanager "ndk;${{ env.NDK_VERSION }}"
      
      - name: Install ebitenmobile
        run: |
          go install github.com/hajimehoshi/ebiten/v2/cmd/ebitenmobile@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Build Android AAR
        run: ./scripts/build-android.sh aar
      
      - name: Build Debug APK
        if: github.event.inputs.build_type != 'release'
        run: ./scripts/build-android.sh apk
      
      - name: Build Release APK
        if: github.event.inputs.build_type == 'release'
        env:
          VENTURE_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          VENTURE_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          VENTURE_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          VENTURE_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          # Decode keystore from base64 secret
          echo "$VENTURE_KEYSTORE_FILE" | base64 -d > keystore.jks
          export VENTURE_KEYSTORE_FILE=keystore.jks
          ./scripts/build-android.sh apk-release
      
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: dist/android/*.apk
          retention-days: 30
      
      - name: Upload AAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-aar
          path: build/android/libs/*.aar
          retention-days: 30
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/android/*.apk
            build/android/libs/*.aar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
