---
name: Build

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    name: Build artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
          - goos: darwin
            goarch: amd64
          - goos: darwin
            goarch: arm64
          - goos: windows
            goarch: amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt-get install libc6-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev libasound2-dev pkg-config

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Download dependencies
        run: go mod download

      - name: Build server
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p build
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then
            EXT=".exe"
          fi
          OUTPUT_NAME="build/venture-server-${{ matrix.goos }}-${{ matrix.goarch }}${EXT}"
          go build -tags test -ldflags="-s -w" -o "${OUTPUT_NAME}" ./cmd/server

      - name: Build client
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p build
          EXT=""
          if [ "${{ matrix.goos }}" = "windows" ]; then
            EXT=".exe"
          fi
          OUTPUT_NAME="build/venture-client-${{ matrix.goos }}-${{ matrix.goarch }}${EXT}"
          go build -ldflags="-s -w" -o "${OUTPUT_NAME}" ./cmd/client

      - name: Upload server artifacts
        uses: actions/upload-artifact@v4
        with:
          name: venture-server-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/venture-server-*
          retention-days: 7

      - name: Upload client artifacts
        uses: actions/upload-artifact@v4
        with:
          name: venture-client-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/venture-client-*
          retention-days: 7

