name: iOS XCFramework Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

env:
  GO_VERSION: '1.24.7'
  XCODE_VERSION: '15.0'

jobs:
  build:
    name: Build iOS App
    runs-on: macos-13
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      
      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app/Contents/Developer
      
      - name: Show Xcode version
        run: xcodebuild -version
      
      - name: Install ebitenmobile
        run: |
          go install github.com/hajimehoshi/ebiten/v2/cmd/ebitenmobile@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Build XCFramework
        run: ./scripts/build-ios.sh xcframework
      
      - name: Create dist directory
        run: mkdir -p dist/ios
      
      - name: Package XCFramework
        run: |
          cd build/ios
          zip -r ../../dist/ios/Venture.xcframework.zip Mobile.xcframework
      
      - name: Upload XCFramework artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-xcframework
          path: dist/ios/Venture.xcframework.zip
          retention-days: 30
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/ios/Venture.xcframework.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
